// demo-vue/app/components/Home.vue
<template>
  <Page class="page">
    <ActionBar class="action-bar">
      <Label class="action-bar-title" text="Home"></Label>
    </ActionBar>

    <GridLayout rows="* auto">
      <StackLayout row="0" class="p-20">
        <GridLayout v-for="(item, index) in selectedItems" :key="index" rows="auto">
          <Label :text="item" class="text-center p-10" textWrap="true" />
        </GridLayout>
      </StackLayout>

      <StackLayout row="1" class="p-10">
        <Button class="btn btn-primary" text="select" @tap="onSelectTapped"></Button>
      </StackLayout>
    </GridLayout>
  </Page>
</template>

<script>
import {
  MultiSelect,
  AShowType
} from "@codelab/nativescript-multi-select";
const MSelect = new MultiSelect();

export default {
  data() {
    return {
      selectedItems: ["moi-a", "moi-b"]
    }
  },
  methods: {
    onSelectTapped() {
      const that = this;
      const options = {
        title: "Please Select",
        selectedItems: this.selectedItems,
        items: [{
            name: "A",
            value: "moi-a"
          },
          {
            name: "B",
            value: "moi-b"
          },
          {
            name: "C",
            value: "moi-c"
          },
          {
            name: "D",
            value: "moi-d"
          }
        ],
        bindValue: "value",
        displayLabel: "name",
        onConfirm: _selectedItems => {
          that.selectedItems = _selectedItems;
          console.log("SELECTED ITEMS => ", _selectedItems);
        },
        onItemSelected: selectedItem => {
          console.log("SELECTED ITEM => ", selectedItem);
        },
        onCancel: () => {
          console.log("CANCEL");
        },
        android: {
          titleSize: 25,
          cancelButtonTextColor: "#252323",
          confirmButtonTextColor: "#70798C"
        },
        ios: {
          cancelButtonBgColor: "#252323",
          confirmButtonBgColor: "#70798C",
          cancelButtonTextColor: "#ffffff",
          confirmButtonTextColor: "#ffffff",
          showType: AShowType.TypeBounceIn
        }
      };

      MSelect.show(options);
    }
  }
};
</script>

<style scoped lang="scss">

</style>

// demo-ng/src/app/home/home.component.ts
import { Component, OnInit, NgZone } from "@angular/core";
import { MultiSelect, AShowType, MSOption } from '@codelab/nativescript-multi-select';

@Component({
  selector: "Home",
  moduleId: module.id,
  templateUrl: "./home.component.html"
})
export class HomeComponent implements OnInit {

  private _MSelect: MultiSelect;
  private predefinedItems: Array<any>;
  public selectedItems: Array<any>;

  constructor(private zone: NgZone) {
    // Use the component constructor to inject providers.
    this._MSelect = new MultiSelect();
    this.predefinedItems = ["moi-a", "moi-b"];
  }

  ngOnInit(): void {
    // Init your component properties here.
  }

  public onSelectTapped(): void {
    const options: MSOption = {
      title: "Please Select",
      selectedItems: this.predefinedItems,
      items: [
        { name: "A", value: "moi-a" },
        { name: "B", value: "moi-b" },
        { name: "C", value: "moi-c" },
        { name: "D", value: "moi-d" },
      ],
      bindValue: 'value',
      displayLabel: 'name',
      onConfirm: selectedItems => {
        this.zone.run(() => {
          this.selectedItems = selectedItems;
          this.predefinedItems = selectedItems;
          console.log("SELECTED ITEMS => ", selectedItems);
        })
      },
      onItemSelected: selectedItem => {
        console.log("SELECTED ITEM => ", selectedItem);
      },
      onCancel: () => {
        console.log('CANCEL');
      },
      android: {
        titleSize: 25,
        cancelButtonTextColor: "#252323",
        confirmButtonTextColor: "#70798C",
      },
      ios: {
        cancelButtonBgColor: "#252323",
        confirmButtonBgColor: "#70798C",
        cancelButtonTextColor: "#ffffff",
        confirmButtonTextColor: "#ffffff",
        showType: AShowType.TypeBounceIn
      }
    };

    this._MSelect.show(options);
  }
}
